### ISSUE TITLE
Scrapy 版本

### ISSUE THREAD

**Issue by JIMhackKING** [lzjqsdd/NewsSpider#6]
你用的是什么 Scrapy 版本？起码要再README里面说明一下你的环境，或者给一个requirement.txt，至少想看看你的代码运行效果的人也能很快搭建好环境很快上手

**Comment by JIMhackKING** [comment]
已提交pull request

**Comment by banyiluoyun** [comment]
伸手党为啥还这么理直气壮？？？？？

**Comment by JIMhackKING** [comment]
> 伸手党为啥还这么理直气壮？？？？？

我看你对伸手党有点误解吧这位“程序员”，至少我有对产品提出建议，开发者就是要想着产品优化，最起码最起码，我是觉得这个项目做得好，所以我才会去用，用过之后才会提出建议。

**而且顺便提一句，看到那个已提交pull request的评论了吗，我自己都对项目都做了优化、改进并且提交了改进后的代码，给予了作者一点点帮助**

**伸手党是对你这种只想着搬别人的代码来用，不想着为别人的项目做奉献，并且只做批评不做行动的人的描述**

建议你去看看pull request

**Comment by banyiluoyun** [comment]
首先，我为我没有了解全部情形而指责你的行为道歉！我确实没有看到pull request，其次我为您指责我才是真正的伸手党辩解。其一，我没有对此项目进行贡献是事实，我在学习中也是事实，力所不逮时强行贡献，一会出丑，二是对作者的侮辱。其二，在下虽然star了不少项目，却未曾搬运任何代码，所有代码不过浏览思路，验证自己代码可行性而已。以上

**Comment by banyiluoyun** [comment]
顺便说一句，之所以会指责，无外乎所有的issue看下来，就您这边语气最不谐，仅此而已。对于贡献表示理解不表示赞同，就这样

**Comment by JIMhackKING** [comment]
我为我的不当措辞道歉，我确实不应该用这种批评的语气来提交issue，同时我也非常赞同你的说法

**Comment by lzjqsdd** [comment]
@JIMhackKING @banyiluoyun 感谢二位都这个项目的关注，二位的争论其实都是为了让项目更容易被其他人接受。工作后也确实发现一个好的文档说明是非常重要的，比如Apache热门的开源项目都可以看到在文档上下的功夫，谢谢~
